__author__ = 'MacbookPro'
import Gnuplot

def create_valence_plot_fig3_aversive(x1,x2):
    g = Gnuplot.Gnuplot(persist=0)
    a = 50
    b = 50
    label1 = 'set label "x" at '+str(x1[0])+','+str(x1[1])+' front'
    label2 = 'set label "x" at '+str(x2[0])+','+str(x2[1])+' front'
    g = Gnuplot.Gnuplot(persist=0)
    #g('set terminal postscript enhanced color eps "Times-Roman" 22   ')
    g('set terminal png')
    g('unset colorbox')
    g('filename="fig3_aversive.png"')
    g('set output filename')
    g('f(x,y) = 1*x + -1*y')
    g('set xrange[0 : 70]')
    g('set yrange[0 : 70]')
    g('set palette file "palete.pal"')
    g('set pm3d map')
    g('set isosamples 50')
    g('set grid ytics lt 0 lw 1 lc rgb "#bbbbbb"')
    g('set grid xtics lt 0 lw 1 lc rgb "#bbbbbb"')
    #g('set label "x" at 35,35 front')
    g(label1)
    g(label2)
    #g('set label "x" at 22 ,35 front')
    #g.set_label("x",offset=(40,40),s='front')
    g('set xlabel "M4 Approach (Hz)"')
    g('set ylabel "MBON Retreat (Hz)"')
    g('splot f(x,y)')

    g('set terminal postscript enhanced color eps "Times-Roman" 22    ')
    g('filename="fig3_aversive.eps"')
    g('set output filename')
    g('f(x,y) = 1*x + -1*y')
    g('set xrange[0 : 70]')
    g('set yrange[0 : 70]')
    g('set palette file "palete.pal"')
    g('set pm3d map')
    g('set isosamples 50')
    g('set grid ytics lt 0 lw 1 lc rgb "#bbbbbb"')
    g('set grid xtics lt 0 lw 1 lc rgb "#bbbbbb"')
    #g('set label "x" at 35,35 front')
    g(label1)
    g(label2)
    #g('set label "x" at 22 ,35 front')
    #g.set_label("x",offset=(40,40),s='front')
    g('set xlabel "MBON Approach (Hz)"')
    g('set ylabel "MBON Retreat (Hz)"')
    g('splot f(x,y)')

    #import matplotlib.image as mpimg
    #img=mpimg.imread('fig3_aversive.png')
    #plt.axis("off")
    #imgplot = plt.imshow(img)

def create_valence_plot_fig3_appetitive(x1,x2):
    import Gnuplot
    g = Gnuplot.Gnuplot(persist=0)
    a = 50
    b = 50
    label1 = 'set label "x" at '+str(x1[0])+','+str(x1[1])+' front'
    label2 = 'set label "x" at '+str(x2[0])+','+str(x2[1])+' front'
    import Gnuplot
    g = Gnuplot.Gnuplot(persist=0)
    #g('set terminal postscript enhanced color eps "Times-Roman" 22   ')
    g('set terminal png')
    g('unset colorbox')
    g('filename="fig3_app.png"')
    g('set output filename')
    g('f(x,y) = 1*x + -1*y')
    g('set xrange[0 : 70]')
    g('set yrange[0 : 70]')
    g('set palette file "palete.pal"')
    g('set pm3d map')
    g('set isosamples 50')
    g('set grid ytics lt 0 lw 1 lc rgb "#bbbbbb"')
    g('set grid xtics lt 0 lw 1 lc rgb "#bbbbbb"')
    #g('set label "x" at 35,35 front')
    g(label1)
    g(label2)
    #g('set label "x" at 22 ,35 front')
    #g.set_label("x",offset=(40,40),s='front')
    g('set xlabel "MBON Approach (Hz)"')
    g('set ylabel "MBON Retreat (Hz)"')
    g('splot f(x,y)')

    g('set terminal postscript enhanced color eps "Times-Roman" 22    ')
    g('filename="fig3_app.eps"')
    g('set output filename')
    g('f(x,y) = 1*x + -1*y')
    g('set xrange[0 : 70]')
    g('set yrange[0 : 70]')
    g('set palette file "palete.pal"')
    g('set pm3d map')
    g('set isosamples 50')
    g('set grid ytics lt 0 lw 1 lc rgb "#bbbbbb"')
    g('set grid xtics lt 0 lw 1 lc rgb "#bbbbbb"')
    #g('set label "x" at 35,35 front')
    g(label1)
    g(label2)
    #g('set label "x" at 22 ,35 front')
    #g.set_label("x",offset=(40,40),s='front')
    g('set xlabel "MBON Approach (Hz)"')
    g('set ylabel "MBON Retreat (Hz)"')
    g('splot f(x,y)')

    #import matplotlib.image as mpimg
    #img=mpimg.imread('fig3_aversive.png')
    #plt.axis("off")
    #imgplot = plt.imshow(img)

def create_valence_plot_fig4_lateral(x1,x2):
    import Gnuplot
    g = Gnuplot.Gnuplot(persist=0)
    a = 50
    b = 50
    label1 = 'set label "x" at '+str(x1[0])+','+str(x1[1])+' front'
    label2 = 'set label "x" at '+str(x2[0])+','+str(x2[1])+' front'
    import Gnuplot
    g = Gnuplot.Gnuplot(persist=0)
    #g('set terminal postscript enhanced color eps "Times-Roman" 22   ')
    g('set terminal png')
    g('unset colorbox')
    g('filename="fig4_lateral_coding.png"')
    g('set size 0.95, 0.95')
    g('set output filename')
    g('f(x,y) = 1*x + -1*y')
    g('set xrange[0 : 70]')
    g('set yrange[0 : 70]')
    g('set palette file "palete.pal"')
    g('set pm3d map')
    g('set isosamples 50')
    g('set grid ytics lt 0 lw 1 lc rgb "#bbbbbb"')
    g('set grid xtics lt 0 lw 1 lc rgb "#bbbbbb"')
    #g('set label "x" at 35,35 front')
    g(label1)
    g(label2)
    #g('set label "x" at 22 ,35 front')
    #g.set_label("x",offset=(40,40),s='front')
    g('set xlabel "MBON Approach (Hz)"')
    g('set ylabel "MBON Retreat (Hz)"')
    g('splot f(x,y)')

    g('set terminal postscript enhanced color eps "Times-Roman" 22    ')
    g('filename="fig4_lateral_coding.eps"')
    g('set output filename')
    g('f(x,y) = 1*x + -1*y')
    g('set xrange[0 : 70]')
    g('set yrange[0 : 70]')
    g('set palette file "palete.pal"')
    g('set pm3d map')
    g('set isosamples 50')
    g('set grid ytics lt 0 lw 1 lc rgb "#bbbbbb"')
    g('set grid xtics lt 0 lw 1 lc rgb "#bbbbbb"')
    #g('set label "x" at 35,35 front')
    g(label1)
    g(label2)
    #g('set label "x" at 22 ,35 front')
    #g.set_label("x",offset=(40,40),s='front')
    g('set xlabel "MBON Approach (Hz)"')
    g('set ylabel "MBON Retreat (Hz)"')
    g('splot f(x,y)')

def create_valence_plot_fig4_nolateral(x1,x2):
    import Gnuplot
    g = Gnuplot.Gnuplot(persist=0)
    a = 50
    b = 50
    label1 = 'set label "x" at '+str(x1[0])+','+str(x1[1])+' front'
    label2 = 'set label "x" at '+str(x2[0])+','+str(x2[1])+' front'
    import Gnuplot
    g = Gnuplot.Gnuplot(persist=0)
    #g('set terminal postscript enhanced color eps "Times-Roman" 22   ')
    g('set terminal png')
    g('unset colorbox')
    g('set size 0.95, 0.95')
    g('filename="fig4_nolateral_coding.png"')
    g('set output filename')
    g('f(x,y) = 1*x + -1*y')
    g('set xrange[0 : 70]')
    g('set yrange[0 : 70]')
    g('set palette file "palete.pal"')
    g('set pm3d map')
    g('set isosamples 50')
    g('set grid ytics lt 0 lw 1 lc rgb "#bbbbbb"')
    g('set grid xtics lt 0 lw 1 lc rgb "#bbbbbb"')
    #g('set label "x" at 35,35 front')
    g(label1)
    g(label2)
    #g('set label "x" at 22 ,35 front')
    #g.set_label("x",offset=(40,40),s='front')
    g('set xlabel "MBON Approach (Hz)"')
    g('set ylabel "MBON Retreat (Hz)"')
    g('splot f(x,y)')

    g('set terminal postscript enhanced color eps "Times-Roman" 22    ')
    g('filename="fig4_nolateral_coding.eps"')
    g('set output filename')
    g('f(x,y) = 1*x + -1*y')
    g('set xrange[0 : 70]')
    g('set yrange[0 : 70]')
    g('set palette file "palete.pal"')
    g('set pm3d map')
    g('set isosamples 50')
    g('set grid ytics lt 0 lw 1 lc rgb "#bbbbbb"')
    g('set grid xtics lt 0 lw 1 lc rgb "#bbbbbb"')
    #g('set label "x" at 35,35 front')
    g(label1)
    g(label2)
    #g('set label "x" at 22 ,35 front')
    #g.set_label("x",offset=(40,40),s='front')
    g('set xlabel "MBON Approach (Hz)"')
    g('set ylabel "MBON Retreat (Hz)"')
    g('splot f(x,y)')